### ISSUE TITLE
blocksJSON undefined

### ISSUE THREAD

**Issue by sunilsingh2019** [tomphill/nextjs-wordpress-course#1]
i have found error. 
Server Error
TypeError: Cannot read properties of undefined (reading 'blocksJSON')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
src\pages\index.jsx (29:40) @ getStaticProps

  27 | const defaultProps = {
  28 |   props: {
> 29 |     blocks: JSON.parse(data.pageByUri.blocksJSON),
     |                                      ^
  30 |     data: data || {},
  31 |   },

**Comment by tomphill** [comment]
Hey @sunilsingh2019 - please post any issues to the Q&A on udemy and I will respond in there. Thanks!
